Fix enum-enum conversion warning in RtcDS1302.h
Makuna/Rtc pull request #218
Opened 2024-11-01 10:13 UTC by notnullxyz

RtcDS1302.h was generating a deprecation warning due to bit-wise operations between different enumeration types. Specifically, the warning was:
"bit-wise operation between different enumeration types 'DS1302TcrStatus' and 'DS1302TcrDiodes' is deprecated"

Solution:
1. Modified the enum definiions to explicitly use uint8_t as their underlying type:
   - DS1302TcrResistor
   - DS1302TcrDiodes
   - DS1302TcrStatus

2. Updated the DS1302Tcr_Disabled constant definition to use static_cast<uint8_t>() for eac enum value:
   ```cpp
   const uint8_t DS1302Tcr_Disabled = static_cast<uint8_t>(DS1302TcrStatus_Disabled) | 
                                      static_cast<uint8_t>(DS1302TcrDiodes_Disabled) | 
                                      static_cast<uint8_t>(DS1302TcrResistor_Disabled);

2024-11-01 18:37 UTC, Makuna requested changes
What platforms did you compile for?  Not necessarily test, just make sure it compiles.
Try AVR, ESP8266, ESP32, and an Arm and make sure it compiles for all.

The Enum type base was on newer versions of C++ only.  Some platforms used to not support the newer compilers.

Otherwise looks good.

2024-11-02 08:43 UTC, notnullxyz commented
Fair point!
For build and flash it works on my ESP32 (and the AVR boards UNO, Leonardo...)
I can only succesfully compile (not physically test on ESP8266 (LOLIN's)
The ARM based Due also compiles.
I am confident, but not 100% if I cannot actually flash it to the boards and test physically, but compile they do do.
Apologies for being a bit narrow minded on this approach

2024-11-02 16:16 UTC, Makuna commented
The original intent of the base for enum, was so that the static_cast would not be required.  Did you try it without it?

2024-11-04 04:56 UTC, Makuna approved these changes

2024-11-04 04:56 UTC, merged